spring:
  datasource:
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    username: root
    password: 123456
    url: jdbc:mysql://192.168.253.128:3306/bill
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
#配置mybatisplus
mybatis-plus:
  mapper-locations:
    - classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
  configuration:   #配置日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #指定mybatis的日志输出对象
##日志输出
#logging:
#  level:
#    com.sxt: debug
